### ISSUE TITLE
Wrong HexConst literal

### ISSUE THREAD

**Issue by hongjisung** [SyGuS-Org/benchmarks#1]
According to https://sygus.org/assets/pdf/SyGuS-IF_2.0.pdf,
- Hexadecimals are written with #x followed by a non-empty sequence of(case-insensitive) digits and letters taken from the ranges[A−F]and[0−9].

But, In v2 directory, Hexadecimal letters are taken from the ranges[a-f]

![스크린샷, 2019-05-18 17-40-45](https://user-images.githubusercontent.com/31429770/57967009-72d20d00-7994-11e9-962d-8c21f103da03.png)

**Comment by SaswatPadhi** [comment]
Looks alright to me.

Since it is **case insensitive**, the range is effectively [a-fA-F0-9].
