### ISSUE TITLE
Missing CrCi benchmarks in 2018

### ISSUE THREAD

**Issue by HanielB** [SyGuS-Org/benchmarks#2]
Hello,

The `CrCi` benchmarks from `General` are missing in the 2018 directory (both for versions 1 and 2).

**Comment by SaswatPadhi** [comment]
Thanks for the report, @HanielB.

@ajreynol recently pushed these benchmarks -- they can be found in [lib/General_Track/from_2018/CrCi](../tree/master/lib/General_Track/from_2018/CrCi).

(We recently change the directory structure for this repo and no longer maintain v1 and v2 copies of the benchmarks -- only the "original / submitted" copy and the "competition / post-processed" copy.)
