### ISSUE TITLE
inv benchmarks parsing errors

### ISSUE THREAD

**Issue by polgreen** [SyGuS-Org/benchmarks#5]
I think there are errors in the let expressions in the benchmarks in https://github.com/SyGuS-Org/benchmarks/tree/master/lib/Inv_Track/andrew_lustre. 

The parsing error is:
~~~
(error "Parse Error: DRAGON_1.lus.sl:740.10: Symbol Bool is not declared.

        Bool (let
        ^
")
~~~
The expression is:
~~~
   (let
    ((X1
      Bool (let
            ((X1 Int DRAGON.res.nondet_4)
             (X2 Int DRAGON.res.nondet_3)
             (X3 Int DRAGON.res.nondet_2)
             (X4 Int DRAGON.res.nondet_1)
             (X5 Int DRAGON.res.nondet_0))
            (and
             (and (and (and (>= X5 1) (= X4 0)) (= X3 0)) (= X2 0))
             (= X1 0)))))
~~~
And I think it should read:
~~~
   (let
    ((X1
       (let
            ((X1  DRAGON.res.nondet_4)
             (X2  DRAGON.res.nondet_3)
             (X3  DRAGON.res.nondet_2)
             (X4  DRAGON.res.nondet_1)
             (X5  DRAGON.res.nondet_0))
            (and
             (and (and (and (>= X5 1) (= X4 0)) (= X3 0)) (= X2 0))
             (= X1 0)))))
~~~

Is this what was intended? And is it possible to regenerate the benchmarks from the source without these errors, or do we need to fix the files we have?

**Comment by SaswatPadhi** [comment]
Hi @polgreen ,

In the old (v1) SyGuS format, the let expressions had a slightly different syntax and required the return type to be specified as well.

At some point (before the next SyGuS-Comp) we would convert this entire repo to the new v2 format (and would archive the v1 benchmarks).

**Comment by SaswatPadhi** [comment]
In the meantime, if you require the v2 versions of these benchmarks, you could use our scripts available in the [tools repo](../../tools) for translation. If you face any issues, please let me know.

**Comment by SaswatPadhi** [comment]
Closing this issue since #6 upgrades all benchmarks to v2,
